version: "3"

services:
    app:
        build: .
        container_name: app
        restart: always
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - 8000:8000
        env_file:
            - ./app.env
        volumes:
            - ./app:/code/app
        networks:
            - urlshortener
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: db
        restart: always
        ports:
            - 3306:3306
        env_file:
            - ./db.env
        volumes:
            - ./db_data:/var/lib/mysql
            - ./database_init.sql:/docker-entrypoint-initdb.d/001_init_db.sql
        networks:
            - urlshortener

networks:
    urlshortener:
        name: url-shortener
